// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace TabTest
{
    public partial class SeafarerdocumentsubmissionContext : DbContext
    {
        public SeafarerdocumentsubmissionContext()
        {
        }

        public SeafarerdocumentsubmissionContext(DbContextOptions<SeafarerdocumentsubmissionContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CertificateType> CertificateTypes { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Submission> Submissions { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("ADD YOUR CONNECTION STRING HERE");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<CertificateType>(entity =>
            {
                entity.ToTable("CertificateType");

                entity.Property(e => e.CertificateTypeId).ValueGeneratedNever();

                entity.Property(e => e.CertificateTypeCd)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("CertificateTypeCD");

                entity.Property(e => e.NameEnglish).IsUnicode(false);

                entity.Property(e => e.NameFrench).IsUnicode(false);
            });

            modelBuilder.Entity<Document>(entity =>
            {
                entity.ToTable("Document");

                entity.Property(e => e.DocumentId)
                    .ValueGeneratedNever()
                    .HasColumnName("DocumentID");

                entity.Property(e => e.Description).HasMaxLength(50);

                entity.Property(e => e.FileName).HasMaxLength(100);

                entity.Property(e => e.FileTypeExtention).HasMaxLength(50);

                entity.Property(e => e.SubmissionId).HasColumnName("SubmissionID");

                entity.HasOne(d => d.Submission)
                    .WithMany(p => p.Documents)
                    .HasForeignKey(d => d.SubmissionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Document_Submission");
            });

            modelBuilder.Entity<Submission>(entity =>
            {
                entity.ToTable("Submission");

                entity.Property(e => e.SubmissionId)
                    .ValueGeneratedNever()
                    .HasColumnName("SubmissionID");

                entity.Property(e => e.CdnNumber)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("CDN_Number");

                entity.Property(e => e.CertificateTypeId).HasColumnName("CertificateTypeID");

                entity.Property(e => e.IsTransferredToMpdis).HasColumnName("IsTransferredToMPDIS");

                entity.Property(e => e.MtaServiveRequestId)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("MTA_ServiveRequestID")
                    .IsFixedLength(true);

                entity.Property(e => e.Note).IsUnicode(false);

                entity.Property(e => e.SubmissionDate).HasColumnType("datetime");

                entity.HasOne(d => d.CertificateType)
                    .WithMany(p => p.Submissions)
                    .HasForeignKey(d => d.CertificateTypeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Submission_CertificateType");
            });

            modelBuilder.HasSequence("Next_Confirmation_Number").StartsAt(1000);

            modelBuilder.HasSequence("Next_Submission_Id");

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}