// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TabTest
{
    public partial class Submission
    {
        public Submission()
        {
            Documents = new HashSet<Document>();
        }

        public int SubmissionId { get; set; }
        public string CdnNumber { get; set; }
        public int CertificateTypeId { get; set; }
        public string MtaServiveRequestId { get; set; }
        public int SubmissionType { get; set; }
        public int ConfirmationNumber { get; set; }
        public string Note { get; set; }
        public int IsTransferredToMpdis { get; set; }
        public DateTime SubmissionDate { get; set; }

        public virtual CertificateType CertificateType { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
    }
}